import { AiSettingsRepository } from '~/repositories/ai-settings.server';
import { callAiProvider } from '~/services/ai-provider.server';
import { normalizeMachineSteps, type PicoRecipeStep, type RawPicoStep } from '~/utils/pico-recipe-validation';

// AI-powered recipe drafting/editing for the "AI Brewmaster" sidekick in both recipe editors (see
// app/pages/RecipeEditor/PicoPackEditor.tsx and app/pages/RecipeEditor/index.tsx). This is a
// single well-scoped prompt + structured-JSON-output call per action, not an agent — each action
// ("draft a recipe from this description" / "apply this change to the current recipe") is
// one-shot with no need for tool use, retrieval, or multi-step planning, so a bigger pipeline
// would only add latency and failure surface for no quality gain.
//
// Output contract: the model is asked for one JSON envelope
// `{ "recipe": {...}, "explanation": "...", "suggestions": [...] }` where "recipe" matches
// PicoPackAiRecipe or ZPackAiRecipe (below) and nothing else. That JSON is untrusted model output
// — it's defensively parsed (stripping markdown fences models sometimes wrap it in) and every
// field is coerced/defaulted rather than trusted, and the machine `steps` program is always run
// through normalizeMachineSteps (for BOTH a fresh generation and an edit — an edit can touch or
// shift those steps too) so the result satisfies validatePicoRecipe regardless of what the model
// produced (see that function's own comment for why prompting alone isn't relied on for that).
// "suggestions" (3-4 short follow-up tweaks, tailored to the just-produced recipe) is generated by
// this same call rather than a second round-trip — the sidekick UI shows them as the next round of
// suggestion chips.

export type PackKind = 'picopack' | 'zpack';

export type AiIngredientRow = {
  name: string;
  amount?: number;
  unit?: string;
  color?: number;
  aa?: number;
  time?: number;
  temp?: number;
  days?: number;
  hours?: number;
};

export type PicoPackAiRecipe = {
  name: string;
  style: string;
  abv: number;
  ibu: number;
  notes: string;
  steps: PicoRecipeStep[];
  // What to load into the physical pak (grain in ounces; hops in ounces with AA%). Optional so a
  // response that leaves them out doesn't wipe the ones already in the editor.
  grains?: AiIngredientRow[];
  hops?: AiIngredientRow[];
};

export type ZPackAiRecipe = PicoPackAiRecipe & {
  og: number;
  fg: number;
  colorSRM: number;
  batchSize: number;
  boilTime: number;
  boilTemp: number;
  firstWortHopping: boolean;
  mashType: number;
  fermentationType: number;
  yeastName: string;
  yeastAttenuation: number;
  yeastRangeTemp: string;
  yeastPitchTemp: number;
  fermentables: AiIngredientRow[];
  mashSteps: AiIngredientRow[];
  hops: AiIngredientRow[];
  dryHops: AiIngredientRow[];
  fermentationSteps: AiIngredientRow[];
};

// Every successful call — generate or edit — returns the recipe plus a short natural-language
// explanation: for a fresh draft, the design approach; for an edit, exactly what changed. The
// editor UI surfaces this as a reply so the user isn't left guessing why the form changed.
// "suggestions" are 3-4 contextual follow-up tweaks for the sidekick's next round of chips.
export type GenerateRecipeResult<T> =
  | { success: true; recipe: T; explanation: string; suggestions: string[] }
  | { success: false; error: string };

// The exact first-3-step convention every hand-authored recipe in this app follows (see
// PicoPackEditor.tsx's DEFAULT_MACHINE_STEPS) and validatePicoRecipe hard-requires. Shown to the
// model as a concrete example rather than described abstractly, per real few-shot examples below.
const LOCATION_LEGEND = '0=Prime, 1=Mash, 2=PassThru, 3=Adjunct1, 4=Adjunct2, 5=Adjunct4, 6=Adjunct3';

const PICOPACK_STEPS_EXAMPLE = `[
  { "name": "Preparing To Brew", "temperature": 70, "stepTime": 3, "drainTime": 0, "location": 0 },
  { "name": "Heating", "temperature": 156, "stepTime": 15, "drainTime": 0, "location": 1 },
  { "name": "Dough In", "temperature": 152, "stepTime": 20, "drainTime": 0, "location": 1 },
  { "name": "Mash 1", "temperature": 152, "stepTime": 30, "drainTime": 0, "location": 1 },
  { "name": "Mash Out", "temperature": 168, "stepTime": 10, "drainTime": 2, "location": 1 },
  { "name": "Hops 1", "temperature": 203, "stepTime": 60, "drainTime": 0, "location": 3 },
  { "name": "Hops 2", "temperature": 203, "stepTime": 15, "drainTime": 0, "location": 4 },
  { "name": "Hops 3", "temperature": 203, "stepTime": 5, "drainTime": 5, "location": 6 }
]`;

// Trimmed from a real hand-authored PicoPak recipe (data/picopak-library/picopaks/1.json,
// "Not Yet-ie Imperial Stout"), with the mandatory first-3-step convention applied the same way
// api.picobrew-recipes.ts's mapPicoPakToRecipeInput applies it when importing that same file.
const PICOPACK_FEWSHOT = `User request: "a big, roasty imperial stout, low-to-moderate bitterness"
JSON response:
{
  "recipe": {
    "name": "Not Yet-ie Imperial Stout",
    "style": "Imperial Stout",
    "abv": 5,
    "ibu": 7,
    "notes": "Full-bodied imperial stout with a roasty backbone. Four late hop additions keep bitterness gentle relative to the malt weight.",
    "grains": [
      { "name": "Pale Malt", "amount": 30 },
      { "name": "Roasted Barley", "amount": 6 },
      { "name": "Chocolate Malt", "amount": 4 }
    ],
    "hops": [
      { "name": "Magnum", "amount": 0.4, "aa": 12 },
      { "name": "East Kent Goldings", "amount": 0.4, "aa": 5 },
      { "name": "Fuggle", "amount": 0.3, "aa": 4.5 },
      { "name": "Fuggle", "amount": 0.3, "aa": 4.5 }
    ],
    "steps": [
      { "name": "Preparing To Brew", "temperature": 70, "stepTime": 3, "drainTime": 0, "location": 0 },
      { "name": "Heating", "temperature": 110, "stepTime": 0, "drainTime": 0, "location": 1 },
      { "name": "Dough In", "temperature": 110, "stepTime": 7, "drainTime": 0, "location": 1 },
      { "name": "Mash 1", "temperature": 148, "stepTime": 25, "drainTime": 0, "location": 1 },
      { "name": "Mash 2", "temperature": 156, "stepTime": 20, "drainTime": 0, "location": 1 },
      { "name": "Mash Out", "temperature": 176, "stepTime": 7, "drainTime": 2, "location": 1 },
      { "name": "Hops 1", "temperature": 203, "stepTime": 10, "drainTime": 0, "location": 3 },
      { "name": "Hops 2", "temperature": 203, "stepTime": 15, "drainTime": 0, "location": 4 },
      { "name": "Hops 3", "temperature": 203, "stepTime": 8, "drainTime": 0, "location": 5 },
      { "name": "Hops 4", "temperature": 203, "stepTime": 7, "drainTime": 5, "location": 6 }
    ]
  },
  "explanation": "Built a roasty imperial stout around a layered dark malt bill with four late, gentle hop additions to keep bitterness in the background.",
  "suggestions": ["add more bitterness", "make it boozier", "add a vanilla/bourbon character", "lighten the body a bit"]
}`;

// Trimmed/adapted from a real ZPak recipe (data/picobrew-recipes/recipes/*.json, "SMaSH Pale
// Mosai v1"), with the machine steps rewritten onto this app's required first-3-step convention.
const ZPACK_FEWSHOT = `User request: "a simple single-hop pale ale"
JSON response:
{
  "recipe": {
    "name": "SMaSH Pale Mosaic",
    "style": "American IPA",
    "abv": 6.2,
    "ibu": 54,
    "og": 1.056,
    "fg": 1.008,
    "colorSRM": 5,
    "notes": "Single malt and single hop pale ale showcasing Mosaic. Dry hop twice, 3 days each, for maximum aroma.",
    "batchSize": 2.5,
    "boilTime": 60,
    "boilTemp": 207,
    "firstWortHopping": false,
    "mashType": 0,
    "fermentationType": 0,
    "yeastName": "Fermentis SafAle US-05",
    "yeastAttenuation": 78,
    "yeastRangeTemp": "64-82",
    "yeastPitchTemp": 65,
    "fermentables": [
      { "name": "American Two-Row Pale", "amount": 7.5, "color": 1.8 }
    ],
    "mashSteps": [
      { "name": "Single Step Infusion Mash", "temp": 152, "time": 90 }
    ],
    "hops": [
      { "name": "Mosaic", "amount": 0.5, "aa": 10.5, "time": 30 },
      { "name": "Mosaic", "amount": 0.5, "aa": 10.5, "time": 20 },
      { "name": "Mosaic", "amount": 0.5, "aa": 10.5, "time": 10 }
    ],
    "dryHops": [
      { "name": "Mosaic", "amount": 0.5, "aa": 10.5, "time": 3 },
      { "name": "Mosaic", "amount": 0.5, "aa": 10.5, "time": 3 }
    ],
    "fermentationSteps": [
      { "name": "Fermentation", "temp": 65, "days": 10, "hours": 0 },
      { "name": "Crash Chill", "temp": 44, "days": 0, "hours": 0 }
    ],
    "steps": ${PICOPACK_STEPS_EXAMPLE}
  },
  "explanation": "Built around a single Mosaic addition across the boil and two dry hop charges for a clean single-hop showcase.",
  "suggestions": ["add more bitterness", "make it maltier", "try a different hop variety", "bump the ABV a bit"]
}`;

// Shown only in edit mode: demonstrates the envelope format for a targeted change — preserving
// everything not asked about, touching only what the instruction implies, and describing exactly
// what changed. Deliberately schema-agnostic (a minimal PicoPack-shaped recipe) since the same
// pattern applies to ZPack's larger shape.
const EDIT_FEWSHOT = `Current recipe (JSON):
{ "name": "Simple Pale Ale", "style": "American Pale Ale", "abv": 5.2, "ibu": 25, "notes": "Clean, balanced pale ale.", "steps": [
  { "name": "Preparing To Brew", "temperature": 70, "stepTime": 3, "drainTime": 0, "location": 0 },
  { "name": "Heating", "temperature": 156, "stepTime": 15, "drainTime": 0, "location": 1 },
  { "name": "Dough In", "temperature": 152, "stepTime": 20, "drainTime": 0, "location": 1 },
  { "name": "Mash 1", "temperature": 152, "stepTime": 40, "drainTime": 0, "location": 1 },
  { "name": "Hops 1", "temperature": 203, "stepTime": 60, "drainTime": 5, "location": 3 }
] }
Requested change: "add more bitterness"
JSON response:
{
  "recipe": {
    "name": "Simple Pale Ale",
    "style": "American Pale Ale",
    "abv": 5.2,
    "ibu": 32,
    "notes": "Clean pale ale with a firmer bittering edge from an added early hop charge.",
    "steps": [
      { "name": "Preparing To Brew", "temperature": 70, "stepTime": 3, "drainTime": 0, "location": 0 },
      { "name": "Heating", "temperature": 156, "stepTime": 15, "drainTime": 0, "location": 1 },
      { "name": "Dough In", "temperature": 152, "stepTime": 20, "drainTime": 0, "location": 1 },
      { "name": "Mash 1", "temperature": 152, "stepTime": 40, "drainTime": 0, "location": 1 },
      { "name": "Hops 1", "temperature": 203, "stepTime": 60, "drainTime": 0, "location": 3 },
      { "name": "Hops 2", "temperature": 203, "stepTime": 45, "drainTime": 5, "location": 4 }
    ]
  },
  "explanation": "I added a second, earlier hop addition (45 minutes left in the boil) to raise the bittering charge, which bumps the estimated IBU from 25 to 32. Everything else is unchanged.",
  "suggestions": ["balance it with more malt character", "bump the ABV too", "make it hoppier in aroma, not just bitterness", "lighten the body a bit"]
}`;

const PERSONA =
  'You are a Brewmaster AI, an expert in home automated brewing on PicoBrew Zymatic/Pico/Z-Series systems. ' +
  'A user describes a beer, or a change to one, in plain language and you respond with a complete, realistic ' +
  "recipe — sensible ingredient choices, mash/boil schedule, and yeast, all consistent with the beer's style " +
  'and target strength/bitterness. Favor common, widely available ingredients over exotic ones unless the ' +
  'request calls for something specific.';

const MACHINE_STEP_RULES = `The recipe's machine "steps" program (what the Pico actually runs) MUST start with exactly these
first 3 steps, in this order — every PicoBrew machine recipe begins this way:
  1. { "name": "Preparing To Brew", "location": 0 } — priming step, always temperature 70, stepTime 3, drainTime 0.
  2. { "name": "Heating", "location": 1 } — heat the mash water.
  3. { "name": "Dough In", "location": 1 } — grain in.
After those 3, add whatever mash/boil/hop-addition steps the recipe needs. Location codes: ${LOCATION_LEGEND}.
drainTime must be 0 on every step EXCEPT a "Mash Out" step or the very last hop-addition step (those may drain).
Temperatures are in °F, stepTime/drainTime are in minutes. These rules apply even when editing an existing
recipe — if your change touches the steps array, the first 3 steps and the drain-time rule still must hold.`;

const EDIT_MODE_RULES = `You are EDITING an existing recipe, not creating one from scratch. You will be given the recipe's
current JSON and a short instruction describing what the user wants changed (e.g. "add more bitterness",
"make this maltier", "increase the ABV a bit", "make it lighter bodied"). Make the smallest realistic change
that satisfies the instruction — adjust or add specific fields/ingredients/steps as needed (e.g. "add more
bitterness" plausibly means adjusting or adding a hop addition's amount/timing, not rewriting the whole
recipe) — and leave every other field exactly as it was unless the change genuinely requires touching it.
Always return the FULL recipe object in "recipe" (every field, not just the ones you changed).`;

function jsonOnlyInstruction(): string {
  return (
    'Respond with ONLY a single JSON object of the exact shape ' +
    '{ "recipe": {...}, "explanation": "...", "suggestions": ["...", "..."] } — no markdown code fences, no ' +
    'text before or after the JSON. "explanation" is at most 2 plain-language sentences a brewer would use.'
  );
}

function explanationFieldMeaning(mode: GenerationMode): string {
  return mode === 'edit'
    ? '"explanation" must describe exactly what you changed and why (e.g. "I increased the Dough In temperature from 152°F to 154°F for a fuller body.").'
    : '"explanation" briefly describes your design approach for the recipe (e.g. "Built around a citrusy Citra/Mosaic combo with a clean, dry fermentation.").';
}

function suggestionsFieldMeaning(): string {
  return (
    '"suggestions" is an array of 3-4 short, specific follow-up tweaks a brewer might want next, each phrased ' +
    'the way a user would type it (e.g. "add more bitterness", "make this maltier", "bump the ABV a bit") — ' +
    "tailored to THIS recipe's current state and style, not a generic filler list, and different from the " +
    'change you just made (if editing).'
  );
}

type GenerationMode = 'generate' | 'edit';

function buildPicoPackSystemPrompt(mode: GenerationMode): string {
  return `${PERSONA}

You are drafting or editing a PicoPak recipe: PicoBrew's format for a fixed 5-liter batch, driven by the machine
step sequence. The "grains" and "hops" lists say what to load into the physical pak: grain goes in the main
compartment (amounts in OUNCES, roughly 20-60 oz total), and each hop is a separate hop compartment (amounts in
OUNCES, AA% is the alpha acid percentage) — one entry per hop-addition step in "steps", in the same order, at most
4. Encode the mash/boil timing in "steps"; yeast guidance goes in "notes".

${MACHINE_STEP_RULES}

${mode === 'edit' ? `${EDIT_MODE_RULES}\n\n` : ''}${jsonOnlyInstruction()} Field meanings: "abv" and "ibu" are
your best numeric estimate for the recipe (not a range). "notes" is AT MOST 2 short sentences covering grain
bill, hop character, and yeast/fermentation guidance — keep it brief, the "steps", "grains" and "hops" arrays
are what matter most. ALWAYS return the complete "grains" and "hops" lists, even when editing (copy the ones the
request doesn't touch unchanged from the current recipe). ${explanationFieldMeaning(mode)} ${suggestionsFieldMeaning()}

Example:
${mode === 'edit' ? EDIT_FEWSHOT : PICOPACK_FEWSHOT}

Required JSON shape:
{
  "recipe": {
    "name": string,
    "style": string,
    "abv": number,
    "ibu": number,
    "notes": string,
    "grains": [ { "name": string, "amount": number } ],
    "hops": [ { "name": string, "amount": number, "aa": number } ],
    "steps": [ { "name": string, "temperature": number, "stepTime": number, "drainTime": number, "location": number } ]
  },
  "explanation": string,
  "suggestions": [string, string, string]
}`;
}

function buildZPackSystemPrompt(mode: GenerationMode): string {
  return `${PERSONA}

You are drafting or editing a ZPack recipe: PicoBrew's full brew-science format, with explicit fermentables,
hop schedule, yeast, mash steps, and target OG/FG/SRM, plus the machine step sequence the Pico runs.

${MACHINE_STEP_RULES}

${mode === 'edit' ? `${EDIT_MODE_RULES}\n\n` : ''}${jsonOnlyInstruction()} Field meanings: "og"/"fg" are
specific gravity (e.g. 1.056); "colorSRM" is color in SRM; "batchSize" is gallons; "boilTime" minutes,
"boilTemp" °F; "mashType" is 0=Single Step Infusion, 1=High Efficiency Multi Step, 2=Custom, 3=Single Step
Infusion With Mash Out; "fermentationType" is 0=Ale, 1=Lager, 2=Advanced/Custom; fermentables "amount" is
pounds and "color" is Lovibond; hops/dryHops "amount" is ounces, "aa" is alpha-acid percent, hops "time" is
boil minutes remaining when added, dryHops "time" is days; fermentationSteps "temp" is °F. Keep every
ingredient list (fermentables, mashSteps, hops, dryHops, fermentationSteps) to at most 5 entries and "notes" to
AT MOST 2 short sentences — the response must stay compact.
${explanationFieldMeaning(mode)} ${suggestionsFieldMeaning()}

Example:
${mode === 'edit' ? EDIT_FEWSHOT : ZPACK_FEWSHOT}

Required JSON shape:
{
  "recipe": {
    "name": string, "style": string, "abv": number, "ibu": number, "notes": string,
    "og": number, "fg": number, "colorSRM": number,
    "batchSize": number, "boilTime": number, "boilTemp": number, "firstWortHopping": boolean,
    "mashType": number, "fermentationType": number,
    "yeastName": string, "yeastAttenuation": number, "yeastRangeTemp": string, "yeastPitchTemp": number,
    "fermentables": [ { "name": string, "amount": number, "color": number } ],
    "mashSteps": [ { "name": string, "temp": number, "time": number } ],
    "hops": [ { "name": string, "amount": number, "aa": number, "time": number } ],
    "dryHops": [ { "name": string, "amount": number, "aa": number, "time": number } ],
    "fermentationSteps": [ { "name": string, "temp": number, "days": number, "hours": number } ],
    "steps": [ { "name": string, "temperature": number, "stepTime": number, "drainTime": number, "location": number } ]
  },
  "explanation": string,
  "suggestions": [string, string, string]
}`;
}

// Models occasionally wrap JSON in a markdown fence or add a sentence of prose around it —
// treated as untrusted output from the surrounding system's perspective, so this defensively
// extracts and parses rather than assuming a clean JSON.parse will work.
function parseJsonResponse(raw: string): Record<string, unknown> | null {
  let text = raw.trim();
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced) {
    text = fenced[1].trim();
  }
  const firstBrace = text.indexOf('{');
  const lastBrace = text.lastIndexOf('}');
  if (firstBrace === -1 || lastBrace === -1 || lastBrace < firstBrace) {
    return null;
  }
  text = text.slice(firstBrace, lastBrace + 1);
  try {
    const parsed = JSON.parse(text);
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

// Unwraps the `{ recipe, explanation, suggestions }` envelope, falling back to treating the whole
// parsed object as the recipe (with no explanation/suggestions) if the model forgot the envelope —
// still untrusted input either way, so normalizePicoPackRecipe/normalizeZPackRecipe coerce every
// field regardless.
function extractEnvelope(parsed: Record<string, unknown>): {
  recipeRaw: Record<string, unknown>;
  explanation: string;
  suggestions: string[];
} {
  const recipeRaw =
    parsed.recipe && typeof parsed.recipe === 'object' ? (parsed.recipe as Record<string, unknown>) : parsed;
  return {
    recipeRaw,
    explanation: str(parsed.explanation).trim(),
    suggestions: sanitizeSuggestions(parsed.suggestions),
  };
}

// Coerces the model's "suggestions" array into a short list of clean, non-empty strings — falls
// back to a small set of generic starters if the model omitted it or returned garbage, so the
// sidekick UI always has something reasonable to show as the next round of chips.
const FALLBACK_SUGGESTIONS = ['add more bitterness', 'make it maltier', 'lighten the body a bit', 'bump the ABV a bit'];

function sanitizeSuggestions(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return FALLBACK_SUGGESTIONS;
  }
  const cleaned = value
    .filter((s): s is string => typeof s === 'string' && s.trim().length > 0)
    .map((s) => s.trim())
    .slice(0, 4);
  return cleaned.length > 0 ? cleaned : FALLBACK_SUGGESTIONS;
}

function str(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function num(value: unknown, fallback: number): number {
  const n = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function boolVal(value: unknown, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback;
}

function rows(value: unknown): AiIngredientRow[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .filter((r): r is Record<string, unknown> => !!r && typeof r === 'object')
    .map((r) => {
      const name = str(r.name).trim();
      if (!name) {
        return null;
      }
      const row: AiIngredientRow = { name };
      if (r.amount != null) {
        row.amount = num(r.amount, 0);
      }
      if (r.unit != null) {
        row.unit = str(r.unit);
      }
      if (r.color != null) {
        row.color = num(r.color, 0);
      }
      if (r.aa != null) {
        row.aa = num(r.aa, 0);
      }
      if (r.time != null) {
        row.time = num(r.time, 0);
      }
      if (r.temp != null) {
        row.temp = num(r.temp, 0);
      }
      if (r.days != null) {
        row.days = num(r.days, 0);
      }
      if (r.hours != null) {
        row.hours = num(r.hours, 0);
      }
      return row;
    })
    .filter((r): r is AiIngredientRow => r !== null);
}

function normalizePicoPackRecipe(parsed: Record<string, unknown>): PicoPackAiRecipe {
  return {
    name: str(parsed.name, 'AI Generated Recipe').trim() || 'AI Generated Recipe',
    style: str(parsed.style).trim(),
    abv: num(parsed.abv, 5),
    ibu: num(parsed.ibu, 30),
    notes: str(parsed.notes).trim(),
    steps: normalizeMachineSteps(parsed.steps as RawPicoStep[] | undefined),
    grains: Array.isArray(parsed.grains) ? rows(parsed.grains) : undefined,
    hops: Array.isArray(parsed.hops) ? rows(parsed.hops) : undefined,
  };
}

function normalizeZPackRecipe(parsed: Record<string, unknown>): ZPackAiRecipe {
  const base = normalizePicoPackRecipe(parsed);
  return {
    ...base,
    og: num(parsed.og, 1.05),
    fg: num(parsed.fg, 1.01),
    colorSRM: num(parsed.colorSRM, 6),
    batchSize: num(parsed.batchSize, 2.5),
    boilTime: num(parsed.boilTime, 60),
    boilTemp: num(parsed.boilTemp, 207),
    firstWortHopping: boolVal(parsed.firstWortHopping, false),
    mashType: num(parsed.mashType, 0),
    fermentationType: num(parsed.fermentationType, 0),
    yeastName: str(parsed.yeastName).trim(),
    yeastAttenuation: num(parsed.yeastAttenuation, 75),
    yeastRangeTemp: str(parsed.yeastRangeTemp).trim(),
    yeastPitchTemp: num(parsed.yeastPitchTemp, 65),
    fermentables: rows(parsed.fermentables),
    mashSteps: rows(parsed.mashSteps),
    hops: rows(parsed.hops),
    dryHops: rows(parsed.dryHops),
    fermentationSteps: rows(parsed.fermentationSteps),
  };
}

type GenerationInput =
  | { mode: 'generate'; prompt: string }
  | { mode: 'edit'; instruction: string; current: PicoPackAiRecipe | ZPackAiRecipe };

type RawGenerationResult =
  | { success: true; recipeRaw: Record<string, unknown>; explanation: string; suggestions: string[] }
  | { success: false; error: string };

async function runGeneration(packKind: PackKind, input: GenerationInput): Promise<RawGenerationResult> {
  const instructionText = input.mode === 'generate' ? input.prompt.trim() : input.instruction.trim();
  if (!instructionText) {
    return {
      success: false,
      error:
        input.mode === 'generate' ? 'Describe the beer you want to brew first.' : 'Describe the change you want first.',
    };
  }
  if (instructionText.length > 2000) {
    return { success: false, error: 'That description is too long — try to keep it under 2000 characters.' };
  }

  const provider = await AiSettingsRepository.getActiveProvider();
  if (!provider) {
    return { success: false, error: 'No AI provider is configured. Add one in Settings → AI.' };
  }

  const system = packKind === 'zpack' ? buildZPackSystemPrompt(input.mode) : buildPicoPackSystemPrompt(input.mode);
  const user =
    input.mode === 'generate'
      ? `Draft a recipe for: ${instructionText}`
      : `Current recipe (JSON):\n${JSON.stringify(input.current)}\n\nRequested change: ${instructionText}`;

  let raw: string;
  try {
    raw = await callAiProvider(provider, {
      system,
      user,
      maxTokens: packKind === 'zpack' ? 6000 : 2200,
      // Recipe drafts/edits are much larger completions than the session advisor's short 2-4
      // sentence replies (ai-advisor.server.ts's default 45s timeout), so this gets more headroom
      // — especially for ZPack's bigger JSON schema (fermentables/hops/yeast/mash on top of steps).
      timeoutMs: packKind === 'zpack' ? 150000 : 90000,
      sessionId: 'repicobrew-recipe-generator',
    });
  } catch (error) {
    console.error('[ai-recipe-generator] request failed', error);
    return { success: false, error: 'The AI request failed. Try again in a moment.' };
  }

  const parsed = parseJsonResponse(raw);
  if (!parsed) {
    console.error('[ai-recipe-generator] could not parse AI response as JSON', raw.slice(0, 500));
    return { success: false, error: 'The AI response could not be understood. Try rephrasing your prompt.' };
  }

  const { recipeRaw, explanation, suggestions } = extractEnvelope(parsed);
  return { success: true, recipeRaw, explanation, suggestions };
}

export async function generatePicoPackRecipe(prompt: string): Promise<GenerateRecipeResult<PicoPackAiRecipe>> {
  const result = await runGeneration('picopack', { mode: 'generate', prompt });
  if (!result.success) {
    return result;
  }
  try {
    return {
      success: true,
      recipe: normalizePicoPackRecipe(result.recipeRaw),
      explanation: result.explanation,
      suggestions: result.suggestions,
    };
  } catch (error) {
    console.error('[ai-recipe-generator] normalization failed', error);
    return { success: false, error: 'The AI response was missing required fields. Try rephrasing your prompt.' };
  }
}

export async function generateZPackRecipe(prompt: string): Promise<GenerateRecipeResult<ZPackAiRecipe>> {
  const result = await runGeneration('zpack', { mode: 'generate', prompt });
  if (!result.success) {
    return result;
  }
  try {
    return {
      success: true,
      recipe: normalizeZPackRecipe(result.recipeRaw),
      explanation: result.explanation,
      suggestions: result.suggestions,
    };
  } catch (error) {
    console.error('[ai-recipe-generator] normalization failed', error);
    return { success: false, error: 'The AI response was missing required fields. Try rephrasing your prompt.' };
  }
}

export async function editPicoPackRecipe(
  current: PicoPackAiRecipe,
  instruction: string,
): Promise<GenerateRecipeResult<PicoPackAiRecipe>> {
  const result = await runGeneration('picopack', { mode: 'edit', instruction, current });
  if (!result.success) {
    return result;
  }
  try {
    return {
      success: true,
      recipe: normalizePicoPackRecipe(result.recipeRaw),
      explanation: result.explanation,
      suggestions: result.suggestions,
    };
  } catch (error) {
    console.error('[ai-recipe-generator] normalization failed', error);
    return { success: false, error: 'The AI response was missing required fields. Try rephrasing your request.' };
  }
}

export async function editZPackRecipe(
  current: ZPackAiRecipe,
  instruction: string,
): Promise<GenerateRecipeResult<ZPackAiRecipe>> {
  const result = await runGeneration('zpack', { mode: 'edit', instruction, current });
  if (!result.success) {
    return result;
  }
  try {
    return {
      success: true,
      recipe: normalizeZPackRecipe(result.recipeRaw),
      explanation: result.explanation,
      suggestions: result.suggestions,
    };
  } catch (error) {
    console.error('[ai-recipe-generator] normalization failed', error);
    return { success: false, error: 'The AI response was missing required fields. Try rephrasing your request.' };
  }
}
