// Beer styles offered in the recipe editors' Style dropdown (BJCP 2021 naming), grouped by family.
export const BEER_STYLE_GROUPS: Array<{ group: string; styles: string[] }> = [
  {
    group: 'Lagers',
    styles: [
      'American Light Lager',
      'American Lager',
      'Cream Ale',
      'Czech Pale Lager',
      'Czech Premium Pale Lager',
      'International Pale Lager',
      'Munich Helles',
      'Festbier',
      'Helles Bock',
      'German Pils',
      'Kellerbier',
      'Märzen',
      'Vienna Lager',
      'Dunkles Bock',
      'Doppelbock',
      'Eisbock',
      'Schwarzbier',
      'Baltic Porter',
      'California Common',
    ],
  },
  {
    group: 'Pale Ales & IPAs',
    styles: [
      'American Pale Ale',
      'American Amber Ale',
      'American IPA',
      'Session IPA',
      'Hazy IPA',
      'Double IPA',
      'Black IPA',
      'Brown IPA',
      'Red IPA',
      'White IPA',
      'Belgian IPA',
      'English IPA',
      'Blonde Ale',
      'Golden Ale',
      'English Pale Ale',
      'Extra Special Bitter',
      'Ordinary Bitter',
      'Best Bitter',
      'Kölsch',
      'Altbier',
    ],
  },
  {
    group: 'Browns, Porters & Stouts',
    styles: [
      'American Brown Ale',
      'English Brown Ale',
      'Brown Porter',
      'Robust Porter',
      'Dry Stout',
      'Sweet Stout',
      'Oatmeal Stout',
      'Foreign Extra Stout',
      'American Stout',
      'Imperial Stout',
      'Pastry Stout',
    ],
  },
  {
    group: 'Wheat & Belgian',
    styles: [
      'American Wheat Beer',
      'Weissbier',
      'Dunkles Weissbier',
      'Weizenbock',
      'Witbier',
      'Belgian Blond Ale',
      'Belgian Pale Ale',
      'Belgian Single',
      'Belgian Dubbel',
      'Belgian Tripel',
      'Belgian Golden Strong Ale',
      'Belgian Dark Strong Ale',
      'Saison',
      'Bière de Garde',
    ],
  },
  {
    group: 'Scottish, Irish & Strong Ales',
    styles: [
      'Irish Red Ale',
      'Scottish Light',
      'Scottish Heavy',
      'Scottish Export',
      'Scotch Ale',
      'Old Ale',
      'English Barleywine',
      'American Barleywine',
      'Wee Heavy',
      'Winter Seasonal Beer',
    ],
  },
  {
    group: 'Sours & Specialty',
    styles: [
      'Berliner Weisse',
      'Gose',
      'Lambic',
      'Flanders Red Ale',
      'Oud Bruin',
      'Fruit Beer',
      'Fruit Lambic',
      'Pumpkin Spice Beer',
      'Spice, Herb, or Vegetable Beer',
      'Smoked Beer',
      'Rauchbier',
      'Specialty Beer',
      'Experimental Beer',
      'Mixed-Style Beer',
      'Non-Alcoholic Beer',
    ],
  },
];
